---
- name: Playbook for security groups
  hosts: localhost
  tasks:
    - name: createa sg 1
      ec2_group:
        name: SecGroup
        description: sg with rule descriptions
        vpc_id: vpc-18730f62
        region: us-east-1
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0            
            
