---
- name: install docker swarm 
  hosts: worker,manager
  become: yes
  become_method: sudo
  gather_facts: true
  tasks:
    - name: install docker swarm
      command: yum install wget -y

    - name: download repo 
      get_url: 
        url: "https://download.docker.com/linux/centos/docker-ce.repo"
        dest: /etc/yum.repos.d/docker.repo
     




    - name: start adn enable docker-swarm
      command: "{{item}}" 
      with_items: 
        - yum install docker-ce -y
        - systemctl start docker
        - systemctl enable docker    


- name: docker init
  hosts: manager
  become: yes
  become_method: sudo 
  tasks: 
    - name: init docker swarm
      command: docker swarm init --advertise-addr 34.221.247.187
      register: dockermanager

    - debug: var=dockermanager.stdout_lines  



           