---
- name: Playbook for provisioning
  hosts: localhost
  gather_facts: no
  tasks:
    - ec2:
        key_name: ansible
        instance_type: t2.micro
        image:  CentOS Linux 7 x86_64 HVM EBS ENA 1901_01-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-05713873c6794f575.4
        group_id: sg-0601a990ce3ebe152
        instance_tags:
          Name: workers
        count: 2
        vpc_subnet_id: subnet-022dca5f
        assign_public_ip: yes
        region: us-west-2


    - ec2:
        key_name: ansible
        instance_type: t2.micro
        image: CentOS Linux 7 x86_64 HVM EBS ENA 1901_01-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-05713873c6794f575.4
        group_id: sg-0601a990ce3ebe152
        instance_tags:
          Name: manager
        count: 1
        vpc_subnet_id: subnet-022dca5f 
        assign_public_ip: yes
        region: us-west-2 