---
- name: Playbook for provisioning
  hosts: localhost
  gather_facts: no
  tasks:
    - ec2:
        key_name: ansible
        instance_type: t2.micro
        image: ami-0316487ff51aefd32
        group: workers
        count: 2
        vpc_subnet_id: subnet-022dca5f
        assign_public_ip: yes
        region: us-west-2


    - ec2:
        key_name: ansible
        instance_type: t2.micro
        image: ami-0316487ff51aefd32
        group: manager
        count: 1
        vpc_subnet_id: subnet-022dca5f 
        assign_public_ip: yes
        region: us-west-2 