---
- name: Playbook for provisioning
  hosts: localhost
  gather_facts: no
  tasks:
    - ec2:
        key_name: ansible
        instance_type: t2.micro
        image: ami-01159062b973a5185
        group_id: sg-0601a990ce3ebe152
        instance_tags:
          Name: workers
        count: 2
        vpc_subnet_id: subnet-022dca5f
        assign_public_ip: yes
        region: us-west-2


    - ec2:
        key_name: ansible
        instance_type: t2.micro
        image: ami-01159062b973a5185
        group_id: sg-0601a990ce3ebe152
        instance_tags:
          Name: manager
        count: 1
        vpc_subnet_id: subnet-022dca5f 
        assign_public_ip: yes
        region: us-west-2 