---
- name: Playbook for provisioning
  hosts: all
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
    - ec2:
        key_name: ansible
        instance_type: t2.micro
        image: ami-0316487ff51aefd32
        group: workers
        count: 2
        vpc_subnet_id: vpc-3e8a3146
        assign_public_ip: yes
        region: us-west-2


    - ec2:
        key_name: ansible
        instance_type: t2.micro
        image: ami-0316487ff51aefd32
        group: manager
        count: 1
        vpc_subnet_id: vpc-3e8a3146
        assign_public_ip: yes
        region: us-west-2 