---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks: 
    - name: download wordpress
      get_url: 
        url: "https://wordpress.org/wordpress-5.2.3.zip"
        dest: /tmp/
    - name: install unzip
      package:
        name: unzip
        state: present
    - name: unzip
      unarchive:
        src: /tmp/wordpress-5.2.3.zip
        dest: /tmp
        remote_src: true
      ignore_errors: true  