---
- name: install LAMP stack
  hosts: all
  become: yes
  become_method: sudo 
  tasks: 
    - name: install multiple packages
      package: 
        name: "{{item}}"
        state: present
      with_items: 
        - httpd
        - mysql
        - mysql-server
        - php7.0
        - php7.0-mysql
- name: start apache
  hosts: all
  become: yes
  become_method: sudo
  service:
    name: httpd
    state: started
    enabled: yes
- name: start mysql
  service:  
    name: mysql
    state: started
    enabled: yes

  


    
