---
- name: install LAMP stack
  hosts: all
  become: yes
  become_method: sudo 
  tasks: 
    - name: install multiple packages
      package: 
        name: "{{item}}"
        state: latest
      with_items: 
        - apache2
        - mysql
        - mysql-server
        - php7.0
        - php7.0-mysql
    - name: start apache
      systemd:
        name: apache2
        state: started
        enabled: yes
    - name: start mysql
      systemd:  
        name: mysql
        state: started
        enabled: yes

  


    
