---
- name: install LAMP stack
  hosts: all
  become: yes
  become_method: sudo 
  tasks: 
    - name: rep
      yum:
        name: centos-release-scl.noarch
        state: present
    - name: install multiple packages
      package: 
        name: "{{item}}"
        state: present
      with_items: 
        - apache
        - mariadb
        - mariadb-server
        - rh-php72
        - rh-php72-php-mysqlnd
    - name: start apache
      systemd:
        name: httpd
        state: restarted
        enabled: yes
    - name: start mysql
      systemd:  
        name: mariadb
        state: restarted
        enabled: yes

  


    
