---
- name: install LAMP stack
  hosts: all
  become: yes
  become_method: sudo 
  tasks: 
    - name: install multiple packages
      package: 
        name: "{{item}}"
        state: present
      with_items: 
        - httpd
        - mariadb
        - mariadb-server
        - php
        - php-mysql
        - php-pdo
        - php-gd
        - php-mbstring
    - name: start apache
      systemd:
        name: httpd
        state: restarted
        enabled: yes
    - name: start mariadb
      systemd:  
        name: httpd
        state: restarted
        enabled: yes
  

  


    
