---
- name: install LAMP stack
  hosts: all
  become: yes
  become_method: sudo 
  tasks: 
    - name: install multiple packages
      package: 
        name: "{{item}}"
        state: latest
      with_items: 
        - httpd
        - mariadb
        - mariadb-server
        - php
        - php-mysql


    
