---
- name: install LAMP stack
  hosts: all
  become: yes
  become_method: sudo 
  tasks: 
    - name: install multiple packages
      package: 
        name: "{{item}}"
        state: latest
      with_items: 
        - httpd
        - mariadb
        - mariadb-server
        - php
        - php-mysql
- name: start apache
  hosts: all
  become: yes
  become_method: sudo
  service:
    name: httpd
    state: started
    enabled: yes
- name: start madiadb
  service:  
    name: mariadb
    state: started
    enabled: yes

  


    
