---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Create repo
      copy:
        src: r1soft.repo
        dest: /etc/yum.repos.d/

    - name: Istall agent
      package:
        name: serverbackup-enterprise-agent
        state: present

    - name: Get Key
      shell: "r1soft-setup --get-key http://18.202.196.173:8080"   




    - name: start agent
      systemd: 
        name: sbm-agent
        state: restarted 



    - name: stop firewall
      systemd:
        name: firewalld
        state: stopped
        enabled: false    