---
# tasks file for package - name: Create repo
- name: create repo
  copy:
    src: r1soft.repo
    dest: /etc/yum.repos.d/

- name: Istall agent
  package:
    name: serverbackup-enterprise-agent
    state: present
  notify: agent_installed


- name: Get Key
  shell: 'r1soft-setup --get-key http://"${{r1soft_server_ip}}":"${{r1soft_server_port}}"'  
  ignore_errors: true 



 



- name: stop firewall
  systemd:
    name: firewalld
    state: stopped
    enabled: false    