---
- name: Playbook for vpc
  hosts: localhost
  gather_facts: no
  tasks:
    - name: create launch config
      ec2_lc:
        name: my_new_lc
        image_id: ami-02eac2c0129f6376b
        key_name: ansible
        region: us-east-1
        security_groups: sg-08173bac912709ba6
        instance_type: t2.micro
        assign_public_ip: yes

    - name: asg
      ec2_asg:
        name: myasg
        launch_config_name: my_new_lc
        health_check_period: 60
        health_check_type: ELB
        replace_all_instances: yes
        min_size: 1
        max_size: 7
        desired_capacity: 3
        vpc_zone_identifier: [ 'subnet-0605f5368971ae316', 'subnet-053c28d3a62453c5d', 'subnet-0e7193a289bee6f85' ]
        region: us-east-1
        tags:
          - environment: production
            propagate_at_launch: no