---
- name: Playbook for vpc
  hosts: localhost
  gather_facts: no
  tasks:
    - name: create igw
      ec2_vpc_igw:
        vpc_id: vpc-01582647ce316875e
        region: us-east-1
        state: present
      register: igw