---
- name: Playbook for route table
  hosts: localhost
  tasks:
    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: vpc-01582647ce316875e
        region: us-east-1
      tags:
        Name: Public
      subnets:
        - subnet-0605f5368971ae316
        - subnet-053c28d3a62453c5d
        - subnet-0e7193a289bee6f85
      routes:
        - dest: 0.0.0.0/0
          gateway_id: igw-09c6fe21b410b8b59
      register: public_route_table