---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  vars:
    users:
    - ais
  tasks:
  - name: create user
    user:
      name: "{{item}}"
    with_items: "{{users}}"    
  - name: add key
    authorized_keys:
      user: "{{item}}"
      key: "{{ lookup('file', 'file/'+ item + '.key.pub') }}"  
    with_items: "{{users}}"  