---
- name: create user with ssh key
  hosts: all
  become: yes
  become_method: sudo
  tasks:
  - include_vars: users.yaml
    - name: pulling keys
      fetch:
        src: /home/"{{username}}"/.ssh/id_rsa.pub
        dest: /tmp/   