---
- name: generate keys
  hosts: all
  become: yes
  become_method: sudo 
  tasks: 
    - name: sshkeygen
      authorized_key: user={{item.username}}
        key="{{lookup('file', 'pub_keys/{{ item.username }}.pub) }}"
      with_items: 
        - max
        - caglar
        - talant
        - enver
        - murat
        - ulan
        - mirlan
        - maksat
        - ali
        - tunji
        - ahmet
        - sera
        - khuslen
        - mahsuda
        - anara
        - mustafa
        - syed
        - ahmed
        - said   

