---
# tasks file for package
- name:  generate key 
  user:
    name: "{{item}}"
    generate_ssh_key: yes
  with_items:
    - ulan
    - miki
    - murat
    - sera
    - mahsuda
    - anara
    - ali
    - mustafa
    - caglar
    - talant
    - max
    - khuslen
    - tunji
    - syed
    - ahmed