---
- name: Playbook for tasks
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tasks: 
    - name: add multiple users
      user: 
        name: "{{item}}"
        state: present  
      with_items:
        - max
        - caglar
        - talant
        - enver
        - murat
        - ulan
        - mirlan
        - maksat
        - ali
        - tunji
        - ahmet
        - sera
        - khuslen
        - mahsuda
        - anara
        - mustafa
        - syed
        - ahmed
        - said        