---
- name: Playbook for tasks
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tasks: 
    - name: add multiple users
      user: 
        name: "{{item}}"
        state: present  
      with_items:
        - ulan
        - miki
        - murat
        - sera
        - mahsuda
        - anara
        - ali
        - mustafa
        - caglar
        - talant
        - max
        - khuslen
        - tunji
        - syed
        - ahmed
