---
- name: pulling keys from remote host to local
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tasks:
    - name: pulling keys
      fetch:  
        src: /home/{{item}}/.ssh/id_rsa.pub
        dest: /tmp/keyfiles/authorized_key.{{item}}.pub
        flat: true
      with_items:
        - max
        - caglar
        - talant
        - enver
        - murat
        - ulan
        - mirlan
        - maksat
        - ali
        - tunji
        - ahmet
        - sera
        - khuslen
        - mahsuda
        - anara
        - mustafa
        - syed
        - ahmed
        - said
        