---
- name: building_structure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks: 
  - include_vars: vars.yaml
  - name: create vpc
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ aws_region }}"
      state: "present"
    register: my_vpc

  - name:  set VPC ID
    set_fact:
      vpc_id: "{{my_vpc.vpc.id}}"




  - name: Create Pb subnet 1
    ec2_vpc_subnet:
      state: "present"
      vpc_id: "{{vpc_id}}"
      cidr: "{{public_subnet_1_cidr"
      az: "{{aws_region}}a"
      region: "{{region}}"    
      resource_tags:
        Name: "public subnet1"
    register: my_public_subnet1  



