---
- name: building_structure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks: 
  - include_vars: vars.yaml
  - name: create vpc
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ aws_region }}"
      state: "present"
    register: my_vpc

  - name:  set VPC ID
    set_fact:
      vpc_id: "{{my_vpc.vpc.id}}"




  - name: Create Pb subnet 1
    ec2_vpc_subnet:
      state: "present"
      vpc_id: "{{my_vpc.vpc.id}}"
      cidr: "{{public_subnet_1_cidr}}"
      az: "{{aws_region}}a"
      region: "{{aws_region}}"    
      resource_tags:
        Name: "public subnet1"
    register: my_public_subnet1  


  - name: 
    set_fact:
      public_subnet_id: "{{my_public_subnet1.subnet.id}}"


  - name: create pb subnet 2
    ec2_vpc_subnet:
      vpc_id: "{{my_vpc.vpc.id}}" 
      cidr: "{{public_subnet_2_cidr}}"
      az: "{{aws_region}}b"
      region: "{{aws_region}}"
      resource_tags:
        Name: "public subnet2" 
    register: my_public_subnet2

  - name: 
    set_fact:
      public_subnet_id: "{{my_public_subnet2.subnet.id}}" 

  - name: create pb subnet 3
    ec2_vpc_subnet: 
      vpc_id: "{{my_vpc.vpc.id}}"
      cidr: "{{public_subnet_3_cidr}}"
      az: "{{aws_region}}c"
      region: "{{aws_region}}"
      resource_tags: 
        Name: "public subnet3"
    register: my_public_subnet3

  - name: 
    set_fact:
      public_subnet_id: "{{my_public_subnet3.subnet.id}}"  




  - name: Create Private subnet 1
    ec2_vpc_subnet:
      state: "present"
      vpc_id: "{{my_vpc.vpc.id}}"
      cidr: "{{private_subnet_1_cidr}}"
      az: "{{aws_region}}a"
      region: "{{aws_region}}"    
      resource_tags:
        Name: "private subnet1"
    register: my_private_subnet1  


  - name: 
    set_fact:
      private_subnet_id: "{{my_private_subnet1.subnet.id}}"


  - name: create private subnet 2
    ec2_vpc_subnet:
      vpc_id: "{{my_vpc.vpc.id}}" 
      cidr: "{{private_subnet_2_cidr}}"
      az: "{{aws_region}}b"
      region: "{{aws_region}}"
      resource_tags:
        Name: "private subnet2" 
    register: my_private_subnet2

  - name: 
    set_fact:
      private_subnet_id: "{{my_private_subnet2.subnet.id}}" 

  - name: create private subnet 3
    ec2_vpc_subnet: 
      vpc_id: "{{my_vpc.vpv.id}}"
      cidr: "{{private_subnet_3_cidr}}"
      az: "{{aws_region}}c"
      region: "{{aws_region}}"
      resources_tags: 
        Name: "private subnet3"
    register: my_private_subnet3

  - name: 
    set_fact:
      private_subnet_id: "{{my_private_subnet3.subnet.id}}"  



