---
- name: building_structure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks: 
  - include_vars: variables.yaml
  - name:               Create VPC
    ec2_vpc_net:
      name:             "{{ vpc_name }}"
      cidr_block:       "{{ vpc_cidr_block }}"
      region:           "{{ aws_region }}"
      state:            "present"
    register: my_vpc

  - name:               Set VPC ID in variable
    set_fact:
      vpc_id:           "{{ my_vpc.vpc.id }}"

  




  - name: Create Pb subnet 1
    ec2_vpc_subnet:
      state: "present"
      vpc_id: "{{my_vpc.vpc.id}}"
      cidr: "{{public_subnet_1_cidr}}"
      az: "{{aws_region}}a"
      region: "{{aws_region}}"    
      resource_tags:
        Name: "public subnet 1"
    register: my_public_subnet_az1 


  
  
            

  

  - name: create pb subnet 2
    ec2_vpc_subnet:
      vpc_id: "{{my_vpc.vpc.id}}" 
      cidr: "{{public_subnet_2_cidr}}"
      az: "{{aws_region}}b"
      region: "{{aws_region}}"
      resource_tags:
        Name: "public subnet 2" 
    register: my_public_subnet_az2





  - name: create pb subnet 3
    ec2_vpc_subnet: 
      vpc_id: "{{my_vpc.vpc.id}}"
      cidr: "{{public_subnet_3_cidr}}"
      az: "{{aws_region}}c"
      region: "{{aws_region}}"
      resource_tags: 
        Name: "public subnet3"
    register: my_public_subnet_az3





  - name: Create Private subnet 1
    ec2_vpc_subnet:
      state: "present"
      vpc_id: "{{my_vpc.vpc.id}}"
      cidr: "{{private_subnet_1_cidr}}"
      az: "{{aws_region}}a"
      region: "{{aws_region}}"    
      resource_tags:
        Name: "private subnet1"
    register: my_private_subnet_az1
  






  - name: create private subnet 2
    ec2_vpc_subnet:
      vpc_id: "{{my_vpc.vpc.id}}" 
      cidr: "{{private_subnet_2_cidr}}"
      az: "{{aws_region}}b"
      region: "{{aws_region}}"
      resource_tags:
        Name: "private subnet2" 
    register: my_private_subnet_az2

 

  - name: create private subnet 3
    ec2_vpc_subnet: 
      vpc_id: "{{my_vpc.vpv.id}}"
      cidr: "{{private_subnet_3_cidr}}"
      az: "{{aws_region}}c"
      region: "{{aws_region}}"
      resources_tags: 
        Name: "private subnet3"
    register: my_private_subnet_az3


      



